config/routes.rb
Rails.application.routes.draw do
  get 'person/index'

  root 'person#index'

  resources :contacts
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def show
		@contact = Contact.find(params[:id])
	end

	def new
	end
	
	def create
		# render plain: params[:contact].inspect
		@contact = Contact.new(params.require(:contact).permit(:name, :phone))
		@contact.save
		redirect_to @contact
	end

end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/contacts/new.html.erb
<h1>Add new contacts here...</h1>
<%= form_for :contact, url: contacts_path do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>

	</p>
	<p>
		<%= f.label :phone %><br/>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/contacts/show.html.erb
<p>
	<b> Name: </b>
	<%= @contact.name %>
</p>
<p>
	<b> Phone: </b>
	<%= @contact.phone %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/person/index.html.erb
<h1>Hello world</h1>